### ISSUE TITLE
Provide bandwidth-free ES6 testdata

### ISSUE THREAD

**Issue by dsnet** [cyberphone/json-canonicalization#16]
This is an alternative to #15.

I'd like to write a test that ensures formatting is canonical for a large suite of numbers, but require no network bandwidth when the test passes.

For the set of floating point numbers chosen in [`es6testfile100m.zip`](https://1drv.ms/u/s!AmhUDQ0Od0GTiXeAjaBJFLJlxyg0?e=HFG4Ao), can the sequence of input numbers be generated with a simple program?

If so, then we can specify a simple program that generates just those numbers, and then have the test generate what would be equivalent to `es6testfile100m.txt` and hash it. If the hash matches, then we have confidence that it passed the test. If it fails, then we have to download the testfile in order to figure which entry differed.

As far as I can tell, there seems to be a pattern for how the first 1144 entries were produced, but everything afterwards appears random. Do we know how the numbers after that point were generated?

**Comment by cyberphone** [comment]
Yes, it is indeed possible to do what you propose.  All it requires is a pseudo-random number generator using a known algorithm so that all testers get the same values.  I'm personally bogged down by related work which is why I haven't been able to progress this.  The original file was created by a cryptographically secure random generator so the result is not repeatable.  I believe 100M pseudo-random 64-bit numbers + the special cases would be entirely sufficient.

**Comment by dsnet** [comment]
[Here's a short Go program](https://play.golang.org/p/6meVPt1bZI_O) that deterministically generates a `es6testfile100m.txt` file. The PRNG is based on SHA-256 since we're going to need a hash anyways.

The generator (i.e., the `next` function) is ~65 lines (~20 for the code itself and ~45 for the global state).

The first 1114 entries of the output are identical to the current [`estestfile100m.zip`](https://1drv.ms/u/s!AmhUDQ0Od0GTiXeAjaBJFLJlxyg0?e=HFG4Ao) dataset.

Here are the SHA-256 hashes of various lengths of outputs:

| **Entries** | **File size** | **File SHA-256 hash** |
| --- | --- | --- |
| 1k | 38054 | ace079ffc98dfc66de4a1ea503baa3fd21dcae86c7fc1a4b7470715c825737f0 |
| 10k | 401124 | e1aead772d79a53df95289caf42f04b0f4fe1cf70058040e27bbd8f03a78b11c |
| 100k | 4033821 | ad12990add6d0b303e356a7aef76c3249ed00ab870fd01ea5d3366630edb48ba |
| 1m | 40359517 | 2b567bd9e82257b5b4ed2bec3e0ecc910722a8566ef0538d0a348c89bf82b9f1 |
| 10m | 403632090 | e48ee378494fa771a9fa109b1b52825cf30bdf4e59601dfc8b4895322d805a8f |
| 100m | 4036328199 | bed4cf9a666be044bbbe243f3465b666d3b9e1def461932f451aad5ad8c07324 |

Using [`compress/gzip`](https://pkg.go.dev/compress/gzip), the file is 2081257067B (1.94GiB) compressed, which should be [just below the 2GiB limit for GitHub releases](https://docs.github.com/en/github/managing-large-files/working-with-large-files/distributing-large-binaries) (to satisfy #15).

**Comment by dsnet** [comment]
Here's a slightly better generator: https://play.golang.org/p/z6QZAyqqg7H

The main difference is that it incorporates all of the entries from Appendix B of the RFC.

**Comment by cyberphone** [comment]
Thanx for your work!
