### ISSUE TITLE
[Python] Support for Python 2.7

### ISSUE THREAD

**Issue by AnasMK** [cyberphone/json-canonicalization#21]
Hey there,

Is there any support for Python 2.7

**Comment by cyberphone** [comment]
Hi @AnasMK, there once was support for Python 2.7 but I removed when the Python authors decided to halt the 2.7 branch.  On the other hand, the existing implementation is very basic so it might very well run in 2.7 as well.   The test programs would verify if that is the case.
Regards,
@cyberphone (Anders)

**Comment by AnasMK** [comment]
Hi @cyberphone, thank you, I really appreciate your quick replay.

I have tried to run tests using python 2.7, there were some syntax errors in `Canonicalize.py`
I did these changes:
1. had to remove bare asterisk argument in JSONEncoder constructor, not supported in 2.7
2. had to change `yeild from` statement to for loop in 5 places 
   - lines: 346, 425, 449, 451, 459
   - All of them have been replaced by this for loop 
   ```python
      for bar in foo: 
          yield bar
    ```
After these changes `verify-canonicalization.py` produce this error:
```
TypeError: Object of type 'unicode' is not JSON serializable
```

Any help to resolve this issue.
Thank you.

**Comment by AnasMK** [comment]
Hi @cyberphone, If you have a local copy of the Python 2.7 branch, it will be much appreciated to upload it again :pray:.

**Comment by cyberphone** [comment]
It seems that I lost that branch during a restructuring.  Usually I put unsupported stuff  in the "historical" repo but this time not 😔

**Comment by cyberphone** [comment]
Hi @AnasMK 
I would consider porting https://github.com/gowebpki/jcs/blob/master/jcs.go as an alternative.
This may be easier to follow canonicalizer: https://github.com/cyberphone/json-canonicalization/blob/master/dotnet/jsoncanonicalizer/JsonCanonicalizer.cs

**Comment by AnasMK** [comment]
Hi,
Thanks for your support @cyberphone, I had successfully ported Python3 code to Python2.7.
- `verify-numbers.py` passed the initial tests, still needs to test with the large text file
- `verify-canonicalization.py` passed all the tests

For anyone is interested in Python 2.7 version I have pushed the code on this [Forked repository](https://github.com/AnasMK/json-canonicalization) 

@cyberphone, Thank you again for your efforts with this repo.

**Comment by cyberphone** [comment]
Thanks and Congratulations!
I will update my JCS info with your implementation.
