### ISSUE TITLE
Rust implementation

### ISSUE THREAD

**Issue by evik42** [cyberphone/json-canonicalization#25]
Hi!

Would you consider adding the rust implementation in the readme so ppl looking for it will have an easier time finding it?
https://crates.io/crates/serde_json_canonicalizer

I used all the test cases from your repository, including the generated one and the ones listed in the RFC including the property sorting one.

**Comment by cyberphone** [comment]
Looks great!
I created a list which now also covers Rust:
https://github.com/cyberphone/json-canonicalization/tree/master#implementations
