### ISSUE TITLE
python module license contains irrelevant info

### ISSUE THREAD

**Issue by caryoscelus** [cyberphone/json-canonicalization#28]
i realize it's probably copypasted from python source, but that means that the text is not applicable here (and contains old python licenses as well as history lesson ^_^)

> This LICENSE AGREEMENT is between the Python Software Foundation
> ("PSF"), and the Individual or Organization ("Licensee") accessing and
> otherwise using this software ("Python") in source or binary form and
> its associated documentation.

**Comment by cyberphone** [comment]
I agree with the change but I think that `Canonicalize.py` should be updated with a reference to PSF 2.0 since it clearly is a moderately modified copy of a Python library file.

**Comment by caryoscelus** [comment]
@cyberphone i've updated PR mentioning PSF
