### ISSUE TITLE
List implementations in README

### ISSUE THREAD

**Issue by Justin-Maxwell** [cyberphone/json-canonicalization#7]
Because I'm dumb and didn't look at the repo folders, I assumed just .js here, and spent 40m looking for Go and Python implementations of JCS. Doh!

I suggest considering an Implementations section in the README, that will hopefully link out to third-party libraries over time, but for now can just reference the various language folder is this repo.

**Comment by silverpill** [comment]
The implementation list has been added recently :+1: 
But these 3rd party libraries are currently missing:
- Ruby https://github.com/dryruby/json-canonicalization
- PHP https://github.com/aywan/php-json-canonicalization

**Comment by cyberphone** [comment]
Done!
Thank you very much for these contributions!
Anders
