### ISSUE TITLE
No NuGet package for dotnet?

### ISSUE THREAD

**Issue by BrightSoul** [cyberphone/json-canonicalization#8]
Please publish this as a NuGet package.

**Comment by cyberphone** [comment]
Thanx, will do, I just need to familiarize myself with NuGet :)

**Comment by drauch** [comment]
Any update on this? :-)

**Comment by cyberphone** [comment]
I think this will have to wait until 1) the spec has become an RFC 2) I have added at least partial support for https://cyberphone.github.io/doc/security/jsf.html and https://cyberphone.github.io/doc/security/jef.html

**Comment by drauch** [comment]
Do I understand correctly, that this is necessary for the signing part of your library only. The canonicalization is already finished and could be published as a Nuget package as is?

**Comment by cyberphone** [comment]
This is 100% correct.

**Comment by drauch** [comment]
What do you think of releasing only the canonicalization library as a NuGet package for now? I'd support you in doing so if you want me to.

**Comment by cyberphone** [comment]
The RFC is ready since 6 months ago but I don't have the time to deal with publishing at this stage.  I also would like to rewrite the number translator to use the Ryu algorithm or investigate if the recent versions of .NET CORE maybe already is compliant.  The previous releases were awfully slow.

**Comment by drauch** [comment]
Nice, what's the name of the NuGet package? :-)

**Comment by cyberphone** [comment]
@drauch @Andorr I must admit that I haven't had the time and motivation to turn this into a NuGet package.  What steps are needed?

**Comment by drauch** [comment]
There is a very nice tutorial @ https://docs.microsoft.com/en-us/nuget/quickstart/create-and-publish-a-package-using-visual-studio?tabs=netcore-cli :)
