### ISSUE TITLE
Add maven pom to java version and publish project to official maven repositories for reuse.

### ISSUE THREAD

**Issue by francis-pouatcha** [cyberphone/json-canonicalization#9]

**Comment by cyberphone** [comment]
Hi @francis-pouatcha, one of my editor-colleges took my code and published it:
https://mvnrepository.com/artifact/io.github.erdtman/java-json-canonicalization/1.1

For those who are more into Nodejs he did such a version as well:
https://www.npmjs.com/package/canonicalize
Npm reports 294,454 weekly downloads, that's crazy  🙃

**Comment by francis-pouatcha** [comment]
Hi @cyberphone this is what i need. I will use the java-json-canonicalization, thank you.
